// Code generated by tools/gen-simd-asm/gen.py; DO NOT EDIT.

//go:build arm64 && simdmatrix

package helpers

import (
	"math"
	"math/rand"
	"testing"
)

// corpus: edge-case lane patterns plus seeded random vectors. The asm
// bodies must agree with the scalar reference on all of them; see
// simdEq for the one sanctioned divergence (which NaN an op returns).
var simdAsmCorpus = func() [][2]uint64 {
	vs := [][2]uint64{
		{0, 0},
		{^uint64(0), ^uint64(0)},
		{0x8080808080808080, 0x8080808080808080},
		{0x8000800080008000, 0x8000800080008000},
		{0x8000000080000000, 0x8000000080000000},
		{0x8000000000000000, 0x8000000000000000},
		{0x7f7f7f7f7f7f7f7f, 0x0101010101010101},
		{0x7fff7fff7fff7fff, 0xffffffffffffffff},
		{0x7fffffff7fffffff, 0x0000000100000001},
		{0x7fc000007fc00000, 0xffc00000ff800001}, // f32 NaNs / -inf+payload
		{0x7ff8000000000000, 0xfff0000000000001}, // f64 NaN / sNaN
		{0x3f8000004048f5c3, 0xc248f5c300000000}, // f32 1.0, pi-ish, -50.24, +0
		{0x4f80000041dfffff, 0xcf000000c1dfffff}, // f32 2^32, near-2^31 bounds
		{0x8000000000000000, 0x0000000000000000}, // f64 -0, +0
		{0x41dfffffffc00000, 0x43f0000000000000}, // f64 2^31-1, 2^64
		{0x0102030405060708, 0x090a0b0c0d0e0f10},
		{0x1011121380402010, 0xfefdfcfb00ff7f80}, // swizzle/shuffle indices
	}
	r := rand.New(rand.NewSource(1))
	for i := 0; i < 32; i++ {
		vs = append(vs, [2]uint64{r.Uint64(), r.Uint64()})
	}
	return vs
}()

var simdAsmShifts = []int32{0, 1, 7, 8, 15, 16, 31, 32, 63, 64, 65, -1}

var simdAsm_vv_v = map[string][2]func([2]uint64, [2]uint64) [2]uint64{
	"simd_f32x4_add": {simd_f32x4_add, simd_f32x4_add_scalar},
	"simd_f32x4_div": {simd_f32x4_div, simd_f32x4_div_scalar},
	"simd_f32x4_eq": {simd_f32x4_eq, simd_f32x4_eq_scalar},
	"simd_f32x4_ge": {simd_f32x4_ge, simd_f32x4_ge_scalar},
	"simd_f32x4_gt": {simd_f32x4_gt, simd_f32x4_gt_scalar},
	"simd_f32x4_le": {simd_f32x4_le, simd_f32x4_le_scalar},
	"simd_f32x4_lt": {simd_f32x4_lt, simd_f32x4_lt_scalar},
	"simd_f32x4_max": {simd_f32x4_max, simd_f32x4_max_scalar},
	"simd_f32x4_min": {simd_f32x4_min, simd_f32x4_min_scalar},
	"simd_f32x4_mul": {simd_f32x4_mul, simd_f32x4_mul_scalar},
	"simd_f32x4_ne": {simd_f32x4_ne, simd_f32x4_ne_scalar},
	"simd_f32x4_pmax": {simd_f32x4_pmax, simd_f32x4_pmax_scalar},
	"simd_f32x4_pmin": {simd_f32x4_pmin, simd_f32x4_pmin_scalar},
	"simd_f32x4_sub": {simd_f32x4_sub, simd_f32x4_sub_scalar},
	"simd_f64x2_add": {simd_f64x2_add, simd_f64x2_add_scalar},
	"simd_f64x2_div": {simd_f64x2_div, simd_f64x2_div_scalar},
	"simd_f64x2_eq": {simd_f64x2_eq, simd_f64x2_eq_scalar},
	"simd_f64x2_ge": {simd_f64x2_ge, simd_f64x2_ge_scalar},
	"simd_f64x2_gt": {simd_f64x2_gt, simd_f64x2_gt_scalar},
	"simd_f64x2_le": {simd_f64x2_le, simd_f64x2_le_scalar},
	"simd_f64x2_lt": {simd_f64x2_lt, simd_f64x2_lt_scalar},
	"simd_f64x2_max": {simd_f64x2_max, simd_f64x2_max_scalar},
	"simd_f64x2_min": {simd_f64x2_min, simd_f64x2_min_scalar},
	"simd_f64x2_mul": {simd_f64x2_mul, simd_f64x2_mul_scalar},
	"simd_f64x2_ne": {simd_f64x2_ne, simd_f64x2_ne_scalar},
	"simd_f64x2_pmax": {simd_f64x2_pmax, simd_f64x2_pmax_scalar},
	"simd_f64x2_pmin": {simd_f64x2_pmin, simd_f64x2_pmin_scalar},
	"simd_f64x2_sub": {simd_f64x2_sub, simd_f64x2_sub_scalar},
	"simd_i16x8_add": {simd_i16x8_add, simd_i16x8_add_scalar},
	"simd_i16x8_add_sat_s": {simd_i16x8_add_sat_s, simd_i16x8_add_sat_s_scalar},
	"simd_i16x8_add_sat_u": {simd_i16x8_add_sat_u, simd_i16x8_add_sat_u_scalar},
	"simd_i16x8_avgr_u": {simd_i16x8_avgr_u, simd_i16x8_avgr_u_scalar},
	"simd_i16x8_eq": {simd_i16x8_eq, simd_i16x8_eq_scalar},
	"simd_i16x8_extmul_high_i8x16_s": {simd_i16x8_extmul_high_i8x16_s, simd_i16x8_extmul_high_i8x16_s_scalar},
	"simd_i16x8_extmul_high_i8x16_u": {simd_i16x8_extmul_high_i8x16_u, simd_i16x8_extmul_high_i8x16_u_scalar},
	"simd_i16x8_extmul_low_i8x16_s": {simd_i16x8_extmul_low_i8x16_s, simd_i16x8_extmul_low_i8x16_s_scalar},
	"simd_i16x8_extmul_low_i8x16_u": {simd_i16x8_extmul_low_i8x16_u, simd_i16x8_extmul_low_i8x16_u_scalar},
	"simd_i16x8_ge_s": {simd_i16x8_ge_s, simd_i16x8_ge_s_scalar},
	"simd_i16x8_ge_u": {simd_i16x8_ge_u, simd_i16x8_ge_u_scalar},
	"simd_i16x8_gt_s": {simd_i16x8_gt_s, simd_i16x8_gt_s_scalar},
	"simd_i16x8_gt_u": {simd_i16x8_gt_u, simd_i16x8_gt_u_scalar},
	"simd_i16x8_le_s": {simd_i16x8_le_s, simd_i16x8_le_s_scalar},
	"simd_i16x8_le_u": {simd_i16x8_le_u, simd_i16x8_le_u_scalar},
	"simd_i16x8_lt_s": {simd_i16x8_lt_s, simd_i16x8_lt_s_scalar},
	"simd_i16x8_lt_u": {simd_i16x8_lt_u, simd_i16x8_lt_u_scalar},
	"simd_i16x8_max_s": {simd_i16x8_max_s, simd_i16x8_max_s_scalar},
	"simd_i16x8_max_u": {simd_i16x8_max_u, simd_i16x8_max_u_scalar},
	"simd_i16x8_min_s": {simd_i16x8_min_s, simd_i16x8_min_s_scalar},
	"simd_i16x8_min_u": {simd_i16x8_min_u, simd_i16x8_min_u_scalar},
	"simd_i16x8_mul": {simd_i16x8_mul, simd_i16x8_mul_scalar},
	"simd_i16x8_narrow_i32x4_s": {simd_i16x8_narrow_i32x4_s, simd_i16x8_narrow_i32x4_s_scalar},
	"simd_i16x8_narrow_i32x4_u": {simd_i16x8_narrow_i32x4_u, simd_i16x8_narrow_i32x4_u_scalar},
	"simd_i16x8_ne": {simd_i16x8_ne, simd_i16x8_ne_scalar},
	"simd_i16x8_q15mulr_sat_s": {simd_i16x8_q15mulr_sat_s, simd_i16x8_q15mulr_sat_s_scalar},
	"simd_i16x8_sub": {simd_i16x8_sub, simd_i16x8_sub_scalar},
	"simd_i16x8_sub_sat_s": {simd_i16x8_sub_sat_s, simd_i16x8_sub_sat_s_scalar},
	"simd_i16x8_sub_sat_u": {simd_i16x8_sub_sat_u, simd_i16x8_sub_sat_u_scalar},
	"simd_i32x4_add": {simd_i32x4_add, simd_i32x4_add_scalar},
	"simd_i32x4_dot_i16x8_s": {simd_i32x4_dot_i16x8_s, simd_i32x4_dot_i16x8_s_scalar},
	"simd_i32x4_eq": {simd_i32x4_eq, simd_i32x4_eq_scalar},
	"simd_i32x4_extmul_high_i16x8_s": {simd_i32x4_extmul_high_i16x8_s, simd_i32x4_extmul_high_i16x8_s_scalar},
	"simd_i32x4_extmul_high_i16x8_u": {simd_i32x4_extmul_high_i16x8_u, simd_i32x4_extmul_high_i16x8_u_scalar},
	"simd_i32x4_extmul_low_i16x8_s": {simd_i32x4_extmul_low_i16x8_s, simd_i32x4_extmul_low_i16x8_s_scalar},
	"simd_i32x4_extmul_low_i16x8_u": {simd_i32x4_extmul_low_i16x8_u, simd_i32x4_extmul_low_i16x8_u_scalar},
	"simd_i32x4_ge_s": {simd_i32x4_ge_s, simd_i32x4_ge_s_scalar},
	"simd_i32x4_ge_u": {simd_i32x4_ge_u, simd_i32x4_ge_u_scalar},
	"simd_i32x4_gt_s": {simd_i32x4_gt_s, simd_i32x4_gt_s_scalar},
	"simd_i32x4_gt_u": {simd_i32x4_gt_u, simd_i32x4_gt_u_scalar},
	"simd_i32x4_le_s": {simd_i32x4_le_s, simd_i32x4_le_s_scalar},
	"simd_i32x4_le_u": {simd_i32x4_le_u, simd_i32x4_le_u_scalar},
	"simd_i32x4_lt_s": {simd_i32x4_lt_s, simd_i32x4_lt_s_scalar},
	"simd_i32x4_lt_u": {simd_i32x4_lt_u, simd_i32x4_lt_u_scalar},
	"simd_i32x4_max_s": {simd_i32x4_max_s, simd_i32x4_max_s_scalar},
	"simd_i32x4_max_u": {simd_i32x4_max_u, simd_i32x4_max_u_scalar},
	"simd_i32x4_min_s": {simd_i32x4_min_s, simd_i32x4_min_s_scalar},
	"simd_i32x4_min_u": {simd_i32x4_min_u, simd_i32x4_min_u_scalar},
	"simd_i32x4_mul": {simd_i32x4_mul, simd_i32x4_mul_scalar},
	"simd_i32x4_ne": {simd_i32x4_ne, simd_i32x4_ne_scalar},
	"simd_i32x4_sub": {simd_i32x4_sub, simd_i32x4_sub_scalar},
	"simd_i64x2_add": {simd_i64x2_add, simd_i64x2_add_scalar},
	"simd_i64x2_eq": {simd_i64x2_eq, simd_i64x2_eq_scalar},
	"simd_i64x2_extmul_high_i32x4_s": {simd_i64x2_extmul_high_i32x4_s, simd_i64x2_extmul_high_i32x4_s_scalar},
	"simd_i64x2_extmul_high_i32x4_u": {simd_i64x2_extmul_high_i32x4_u, simd_i64x2_extmul_high_i32x4_u_scalar},
	"simd_i64x2_extmul_low_i32x4_s": {simd_i64x2_extmul_low_i32x4_s, simd_i64x2_extmul_low_i32x4_s_scalar},
	"simd_i64x2_extmul_low_i32x4_u": {simd_i64x2_extmul_low_i32x4_u, simd_i64x2_extmul_low_i32x4_u_scalar},
	"simd_i64x2_ge_s": {simd_i64x2_ge_s, simd_i64x2_ge_s_scalar},
	"simd_i64x2_gt_s": {simd_i64x2_gt_s, simd_i64x2_gt_s_scalar},
	"simd_i64x2_le_s": {simd_i64x2_le_s, simd_i64x2_le_s_scalar},
	"simd_i64x2_lt_s": {simd_i64x2_lt_s, simd_i64x2_lt_s_scalar},
	"simd_i64x2_ne": {simd_i64x2_ne, simd_i64x2_ne_scalar},
	"simd_i64x2_sub": {simd_i64x2_sub, simd_i64x2_sub_scalar},
	"simd_i8x16_add": {simd_i8x16_add, simd_i8x16_add_scalar},
	"simd_i8x16_add_sat_s": {simd_i8x16_add_sat_s, simd_i8x16_add_sat_s_scalar},
	"simd_i8x16_add_sat_u": {simd_i8x16_add_sat_u, simd_i8x16_add_sat_u_scalar},
	"simd_i8x16_avgr_u": {simd_i8x16_avgr_u, simd_i8x16_avgr_u_scalar},
	"simd_i8x16_eq": {simd_i8x16_eq, simd_i8x16_eq_scalar},
	"simd_i8x16_ge_s": {simd_i8x16_ge_s, simd_i8x16_ge_s_scalar},
	"simd_i8x16_ge_u": {simd_i8x16_ge_u, simd_i8x16_ge_u_scalar},
	"simd_i8x16_gt_s": {simd_i8x16_gt_s, simd_i8x16_gt_s_scalar},
	"simd_i8x16_gt_u": {simd_i8x16_gt_u, simd_i8x16_gt_u_scalar},
	"simd_i8x16_le_s": {simd_i8x16_le_s, simd_i8x16_le_s_scalar},
	"simd_i8x16_le_u": {simd_i8x16_le_u, simd_i8x16_le_u_scalar},
	"simd_i8x16_lt_s": {simd_i8x16_lt_s, simd_i8x16_lt_s_scalar},
	"simd_i8x16_lt_u": {simd_i8x16_lt_u, simd_i8x16_lt_u_scalar},
	"simd_i8x16_max_s": {simd_i8x16_max_s, simd_i8x16_max_s_scalar},
	"simd_i8x16_max_u": {simd_i8x16_max_u, simd_i8x16_max_u_scalar},
	"simd_i8x16_min_s": {simd_i8x16_min_s, simd_i8x16_min_s_scalar},
	"simd_i8x16_min_u": {simd_i8x16_min_u, simd_i8x16_min_u_scalar},
	"simd_i8x16_narrow_i16x8_s": {simd_i8x16_narrow_i16x8_s, simd_i8x16_narrow_i16x8_s_scalar},
	"simd_i8x16_narrow_i16x8_u": {simd_i8x16_narrow_i16x8_u, simd_i8x16_narrow_i16x8_u_scalar},
	"simd_i8x16_ne": {simd_i8x16_ne, simd_i8x16_ne_scalar},
	"simd_i8x16_sub": {simd_i8x16_sub, simd_i8x16_sub_scalar},
	"simd_i8x16_sub_sat_s": {simd_i8x16_sub_sat_s, simd_i8x16_sub_sat_s_scalar},
	"simd_i8x16_sub_sat_u": {simd_i8x16_sub_sat_u, simd_i8x16_sub_sat_u_scalar},
	"simd_i8x16_swizzle": {simd_i8x16_swizzle, simd_i8x16_swizzle_scalar},
	"simd_v128_and": {simd_v128_and, simd_v128_and_scalar},
	"simd_v128_andnot": {simd_v128_andnot, simd_v128_andnot_scalar},
	"simd_v128_or": {simd_v128_or, simd_v128_or_scalar},
	"simd_v128_xor": {simd_v128_xor, simd_v128_xor_scalar},
}

var simdAsm_v_v = map[string][2]func([2]uint64) [2]uint64{
	"simd_f32x4_abs": {simd_f32x4_abs, simd_f32x4_abs_scalar},
	"simd_f32x4_ceil": {simd_f32x4_ceil, simd_f32x4_ceil_scalar},
	"simd_f32x4_convert_i32x4_s": {simd_f32x4_convert_i32x4_s, simd_f32x4_convert_i32x4_s_scalar},
	"simd_f32x4_convert_i32x4_u": {simd_f32x4_convert_i32x4_u, simd_f32x4_convert_i32x4_u_scalar},
	"simd_f32x4_demote_f64x2_zero": {simd_f32x4_demote_f64x2_zero, simd_f32x4_demote_f64x2_zero_scalar},
	"simd_f32x4_floor": {simd_f32x4_floor, simd_f32x4_floor_scalar},
	"simd_f32x4_nearest": {simd_f32x4_nearest, simd_f32x4_nearest_scalar},
	"simd_f32x4_neg": {simd_f32x4_neg, simd_f32x4_neg_scalar},
	"simd_f32x4_sqrt": {simd_f32x4_sqrt, simd_f32x4_sqrt_scalar},
	"simd_f32x4_trunc": {simd_f32x4_trunc, simd_f32x4_trunc_scalar},
	"simd_f64x2_abs": {simd_f64x2_abs, simd_f64x2_abs_scalar},
	"simd_f64x2_ceil": {simd_f64x2_ceil, simd_f64x2_ceil_scalar},
	"simd_f64x2_convert_low_i32x4_s": {simd_f64x2_convert_low_i32x4_s, simd_f64x2_convert_low_i32x4_s_scalar},
	"simd_f64x2_convert_low_i32x4_u": {simd_f64x2_convert_low_i32x4_u, simd_f64x2_convert_low_i32x4_u_scalar},
	"simd_f64x2_floor": {simd_f64x2_floor, simd_f64x2_floor_scalar},
	"simd_f64x2_nearest": {simd_f64x2_nearest, simd_f64x2_nearest_scalar},
	"simd_f64x2_neg": {simd_f64x2_neg, simd_f64x2_neg_scalar},
	"simd_f64x2_promote_low_f32x4": {simd_f64x2_promote_low_f32x4, simd_f64x2_promote_low_f32x4_scalar},
	"simd_f64x2_sqrt": {simd_f64x2_sqrt, simd_f64x2_sqrt_scalar},
	"simd_f64x2_trunc": {simd_f64x2_trunc, simd_f64x2_trunc_scalar},
	"simd_i16x8_abs": {simd_i16x8_abs, simd_i16x8_abs_scalar},
	"simd_i16x8_extadd_pairwise_i8x16_s": {simd_i16x8_extadd_pairwise_i8x16_s, simd_i16x8_extadd_pairwise_i8x16_s_scalar},
	"simd_i16x8_extadd_pairwise_i8x16_u": {simd_i16x8_extadd_pairwise_i8x16_u, simd_i16x8_extadd_pairwise_i8x16_u_scalar},
	"simd_i16x8_extend_high_i8x16_s": {simd_i16x8_extend_high_i8x16_s, simd_i16x8_extend_high_i8x16_s_scalar},
	"simd_i16x8_extend_high_i8x16_u": {simd_i16x8_extend_high_i8x16_u, simd_i16x8_extend_high_i8x16_u_scalar},
	"simd_i16x8_extend_low_i8x16_s": {simd_i16x8_extend_low_i8x16_s, simd_i16x8_extend_low_i8x16_s_scalar},
	"simd_i16x8_extend_low_i8x16_u": {simd_i16x8_extend_low_i8x16_u, simd_i16x8_extend_low_i8x16_u_scalar},
	"simd_i16x8_neg": {simd_i16x8_neg, simd_i16x8_neg_scalar},
	"simd_i32x4_abs": {simd_i32x4_abs, simd_i32x4_abs_scalar},
	"simd_i32x4_extadd_pairwise_i16x8_s": {simd_i32x4_extadd_pairwise_i16x8_s, simd_i32x4_extadd_pairwise_i16x8_s_scalar},
	"simd_i32x4_extadd_pairwise_i16x8_u": {simd_i32x4_extadd_pairwise_i16x8_u, simd_i32x4_extadd_pairwise_i16x8_u_scalar},
	"simd_i32x4_extend_high_i16x8_s": {simd_i32x4_extend_high_i16x8_s, simd_i32x4_extend_high_i16x8_s_scalar},
	"simd_i32x4_extend_high_i16x8_u": {simd_i32x4_extend_high_i16x8_u, simd_i32x4_extend_high_i16x8_u_scalar},
	"simd_i32x4_extend_low_i16x8_s": {simd_i32x4_extend_low_i16x8_s, simd_i32x4_extend_low_i16x8_s_scalar},
	"simd_i32x4_extend_low_i16x8_u": {simd_i32x4_extend_low_i16x8_u, simd_i32x4_extend_low_i16x8_u_scalar},
	"simd_i32x4_neg": {simd_i32x4_neg, simd_i32x4_neg_scalar},
	"simd_i32x4_trunc_sat_f32x4_s": {simd_i32x4_trunc_sat_f32x4_s, simd_i32x4_trunc_sat_f32x4_s_scalar},
	"simd_i32x4_trunc_sat_f32x4_u": {simd_i32x4_trunc_sat_f32x4_u, simd_i32x4_trunc_sat_f32x4_u_scalar},
	"simd_i32x4_trunc_sat_f64x2_s_zero": {simd_i32x4_trunc_sat_f64x2_s_zero, simd_i32x4_trunc_sat_f64x2_s_zero_scalar},
	"simd_i32x4_trunc_sat_f64x2_u_zero": {simd_i32x4_trunc_sat_f64x2_u_zero, simd_i32x4_trunc_sat_f64x2_u_zero_scalar},
	"simd_i64x2_abs": {simd_i64x2_abs, simd_i64x2_abs_scalar},
	"simd_i64x2_extend_high_i32x4_s": {simd_i64x2_extend_high_i32x4_s, simd_i64x2_extend_high_i32x4_s_scalar},
	"simd_i64x2_extend_high_i32x4_u": {simd_i64x2_extend_high_i32x4_u, simd_i64x2_extend_high_i32x4_u_scalar},
	"simd_i64x2_extend_low_i32x4_s": {simd_i64x2_extend_low_i32x4_s, simd_i64x2_extend_low_i32x4_s_scalar},
	"simd_i64x2_extend_low_i32x4_u": {simd_i64x2_extend_low_i32x4_u, simd_i64x2_extend_low_i32x4_u_scalar},
	"simd_i64x2_neg": {simd_i64x2_neg, simd_i64x2_neg_scalar},
	"simd_i8x16_abs": {simd_i8x16_abs, simd_i8x16_abs_scalar},
	"simd_i8x16_neg": {simd_i8x16_neg, simd_i8x16_neg_scalar},
	"simd_i8x16_popcnt": {simd_i8x16_popcnt, simd_i8x16_popcnt_scalar},
	"simd_v128_not": {simd_v128_not, simd_v128_not_scalar},
}

var simdAsm_vvv_v = map[string][2]func([2]uint64, [2]uint64, [2]uint64) [2]uint64{
	"simd_i8x16_shuffle": {simd_i8x16_shuffle, simd_i8x16_shuffle_scalar},
	"simd_v128_bitselect": {simd_v128_bitselect, simd_v128_bitselect_scalar},
}

var simdAsm_vs_v = map[string][2]func([2]uint64, int32) [2]uint64{
	"simd_i16x8_shl": {simd_i16x8_shl, simd_i16x8_shl_scalar},
	"simd_i16x8_shr_s": {simd_i16x8_shr_s, simd_i16x8_shr_s_scalar},
	"simd_i16x8_shr_u": {simd_i16x8_shr_u, simd_i16x8_shr_u_scalar},
	"simd_i32x4_shl": {simd_i32x4_shl, simd_i32x4_shl_scalar},
	"simd_i32x4_shr_s": {simd_i32x4_shr_s, simd_i32x4_shr_s_scalar},
	"simd_i32x4_shr_u": {simd_i32x4_shr_u, simd_i32x4_shr_u_scalar},
	"simd_i64x2_shl": {simd_i64x2_shl, simd_i64x2_shl_scalar},
	"simd_i64x2_shr_s": {simd_i64x2_shr_s, simd_i64x2_shr_s_scalar},
	"simd_i64x2_shr_u": {simd_i64x2_shr_u, simd_i64x2_shr_u_scalar},
	"simd_i8x16_shl": {simd_i8x16_shl, simd_i8x16_shl_scalar},
	"simd_i8x16_shr_s": {simd_i8x16_shr_s, simd_i8x16_shr_s_scalar},
	"simd_i8x16_shr_u": {simd_i8x16_shr_u, simd_i8x16_shr_u_scalar},
}

var simdAsm_v_i32 = map[string][2]func([2]uint64) int32{
	"simd_i16x8_all_true": {simd_i16x8_all_true, simd_i16x8_all_true_scalar},
	"simd_i16x8_bitmask": {simd_i16x8_bitmask, simd_i16x8_bitmask_scalar},
	"simd_i32x4_all_true": {simd_i32x4_all_true, simd_i32x4_all_true_scalar},
	"simd_i32x4_bitmask": {simd_i32x4_bitmask, simd_i32x4_bitmask_scalar},
	"simd_i64x2_all_true": {simd_i64x2_all_true, simd_i64x2_all_true_scalar},
	"simd_i64x2_bitmask": {simd_i64x2_bitmask, simd_i64x2_bitmask_scalar},
	"simd_i8x16_all_true": {simd_i8x16_all_true, simd_i8x16_all_true_scalar},
	"simd_i8x16_bitmask": {simd_i8x16_bitmask, simd_i8x16_bitmask_scalar},
	"simd_v128_any_true": {simd_v128_any_true, simd_v128_any_true_scalar},
}

var simdAsm_v_i64 = map[string][2]func([2]uint64) int64{
	"simd_f16x4_cvt_bits": {simd_f16x4_cvt_bits, simd_f16x4_cvt_bits_scalar},
}

var simdAsm_s32_v = map[string][2]func(int32) [2]uint64{
	"simd_i16x8_splat": {simd_i16x8_splat, simd_i16x8_splat_scalar},
	"simd_i32x4_splat": {simd_i32x4_splat, simd_i32x4_splat_scalar},
	"simd_i8x16_splat": {simd_i8x16_splat, simd_i8x16_splat_scalar},
}

var simdAsm_s64_v = map[string][2]func(int64) [2]uint64{
	"simd_i64x2_splat": {simd_i64x2_splat, simd_i64x2_splat_scalar},
}

var simdAsm_f32_v = map[string][2]func(float32) [2]uint64{
	"simd_f32x4_splat": {simd_f32x4_splat, simd_f32x4_splat_scalar},
}

var simdAsm_f64_v = map[string][2]func(float64) [2]uint64{
	"simd_f64x2_splat": {simd_f64x2_splat, simd_f64x2_splat_scalar},
}

// Which NaN an operation propagates when several operands are NaN is
// nondeterministic in wasm, and for plain float arithmetic it depends on the
// operand order the Go compiler happens to pick for the scalar body. For
// those ops a lane where BOTH sides produced some NaN counts as equal;
// everything else (comparisons, selects, all integer ops) must match
// bit-for-bit.

func nanLanes(name string) int {
	switch name {
	case "simd_f32x4_add", "simd_f32x4_sub", "simd_f32x4_mul", "simd_f32x4_div":
		return 4
	case "simd_f64x2_add", "simd_f64x2_sub", "simd_f64x2_mul", "simd_f64x2_div":
		return 2
	}
	return 0
}

func laneIsNaN(v [2]uint64, lanes, i int) bool {
	if lanes == 4 {
		x := uint32(v[i>>1] >> (32 * uint(i&1)))
		return x&0x7f800000 == 0x7f800000 && x&0x007fffff != 0
	}
	x := v[i]
	return x&0x7ff0000000000000 == 0x7ff0000000000000 && x&0x000fffffffffffff != 0
}

func simdEq(got, want [2]uint64, lanes int) bool {
	if got == want {
		return true
	}
	if lanes == 0 {
		return false
	}
	for i := 0; i < lanes; i++ {
		var g, w uint64
		if lanes == 4 {
			g = uint64(uint32(got[i>>1] >> (32 * uint(i&1))))
			w = uint64(uint32(want[i>>1] >> (32 * uint(i&1))))
		} else {
			g, w = got[i], want[i]
		}
		if g == w {
			continue
		}
		if !laneIsNaN(got, lanes, i) || !laneIsNaN(want, lanes, i) {
			return false
		}
	}
	return true
}

func TestSimdAsmMatchesScalar(t *testing.T) {
	for name, fns := range simdAsm_vv_v {
		lanes := nanLanes(name)
		for _, a := range simdAsmCorpus {
			for _, b := range simdAsmCorpus {
				if got, want := fns[0](a, b), fns[1](a, b); !simdEq(got, want, lanes) {
					t.Fatalf("%s(%x, %x) = %x, scalar %x", name, a, b, got, want)
				}
			}
		}
	}
	for name, fns := range simdAsm_v_v {
		for _, a := range simdAsmCorpus {
			if got, want := fns[0](a), fns[1](a); got != want {
				t.Fatalf("%s(%x) = %x, scalar %x", name, a, got, want)
			}
		}
	}
	for name, fns := range simdAsm_vvv_v {
		for _, a := range simdAsmCorpus {
			for _, b := range simdAsmCorpus {
				c := [2]uint64{a[1] ^ b[0], a[0]}
				if got, want := fns[0](a, b, c), fns[1](a, b, c); got != want {
					t.Fatalf("%s(%x, %x, %x) = %x, scalar %x", name, a, b, c, got, want)
				}
			}
		}
	}
	for name, fns := range simdAsm_vs_v {
		for _, a := range simdAsmCorpus {
			for _, s := range simdAsmShifts {
				if got, want := fns[0](a, s), fns[1](a, s); got != want {
					t.Fatalf("%s(%x, %d) = %x, scalar %x", name, a, s, got, want)
				}
			}
		}
	}
	for name, fns := range simdAsm_v_i32 {
		for _, a := range simdAsmCorpus {
			if got, want := fns[0](a), fns[1](a); got != want {
				t.Fatalf("%s(%x) = %d, scalar %d", name, a, got, want)
			}
		}
	}
	for name, fns := range simdAsm_v_i64 {
		for _, a := range simdAsmCorpus {
			if got, want := fns[0](a), fns[1](a); got != want {
				t.Fatalf("%s(%x) = %#x, scalar %#x", name, a, got, want)
			}
		}
	}
	for name, fns := range simdAsm_s32_v {
		for _, s := range []int32{0, 1, -1, 127, -128, 255, 32767, -32768, 1 << 30, -(1 << 30)} {
			if got, want := fns[0](s), fns[1](s); got != want {
				t.Fatalf("%s(%d) = %x, scalar %x", name, s, got, want)
			}
		}
	}
	for name, fns := range simdAsm_s64_v {
		for _, s := range []int64{0, 1, -1, 1 << 62, -(1 << 62)} {
			if got, want := fns[0](s), fns[1](s); got != want {
				t.Fatalf("%s(%d) = %x, scalar %x", name, s, got, want)
			}
		}
	}
	for name, fns := range simdAsm_f32_v {
		for _, a := range simdAsmCorpus {
			s := math.Float32frombits(uint32(a[0]))
			if got, want := fns[0](s), fns[1](s); got != want {
				t.Fatalf("%s(%v) = %x, scalar %x", name, s, got, want)
			}
		}
	}
	for name, fns := range simdAsm_f64_v {
		for _, a := range simdAsmCorpus {
			s := math.Float64frombits(a[0])
			if got, want := fns[0](s), fns[1](s); got != want {
				t.Fatalf("%s(%v) = %x, scalar %x", name, s, got, want)
			}
		}
	}
}
